import React from "react";
import {
  Bullets,
  Emphasis,
  InfoCard,
  Paragraph,
  SettingsSubScreen,
} from "./SettingsSubScreen";

export default function TermsOfUseScreen() {
  return (
    <SettingsSubScreen
      title="Terms of Use"
      subtitle="Last updated: September 2026. By using STRIX you agree to these terms."
    >
      <InfoCard title="1 · Acceptance">
        <Paragraph>
          STRIX is provided as-is, for your personal use. By installing or
          using the app you accept these terms. If you don't agree, please
          don't use the app.
        </Paragraph>
      </InfoCard>

      <InfoCard title="2 · Personal-use tool">
        <Paragraph>
          STRIX is a personal learning and note-taking tool. It is not
          offered for commercial, educational-institution, medical, legal,
          financial, or safety-critical use, and you may not rely on it in
          place of professional advice. You're responsible for how you use the
          notes and outputs it produces.
        </Paragraph>
      </InfoCard>

      <InfoCard title="3 · AI-generated content">
        <Emphasis>
          AI responses may be inaccurate, incomplete, or out of date — always
          verify important information before relying on it.
        </Emphasis>
        <Paragraph>
          AI features in STRIX are powered by Google's Gemini API and are
          provided for assistance and inspiration only. Output is generated by
          a machine learning model: it can be wrong, biased, or made up
          (hallucinated), and it does not represent the views of the STRIX
          developer.
        </Paragraph>
        <Bullets
          items={[
            "Do not treat AI output as professional advice of any kind.",
            "Check facts, citations, and calculations against a trusted source.",
            "You decide what gets saved into your tree — AI only suggests.",
          ]}
        />
      </InfoCard>

      <InfoCard title="4 · Your Gemini API key, usage, and billing">
        <Paragraph>
          AI features require your own Gemini API key obtained from Google.
          That relationship is between you and Google:
        </Paragraph>
        <Bullets
          items={[
            "You are solely responsible for obtaining, safeguarding, and using your key.",
            "You are responsible for your API usage, quotas, rate limits, and any charges Google bills to your Google Cloud account — STRIX charges nothing and takes no cut.",
            "You must follow Google's terms, pricing, and usage policies for the Gemini API.",
            "If your key is leaked or misused, revoke it in Google AI Studio and generate a new one.",
          ]}
        />
        <Paragraph>
          STRIX stores your key only in your device's secure storage and
          sends it only to Google's API. Removing the key in the app deletes
          it from the device.
        </Paragraph>
      </InfoCard>

      <InfoCard title="5 · Your data and responsibility">
        <Paragraph>
          STRIX stores your content locally on your device with no cloud
          backup. You're responsible for your own data: if you delete the app
          or lose the device, your notes go with it. You are also responsible
          for the content you put into the app and send to the AI, including
          making sure you have the right to share it.
        </Paragraph>
      </InfoCard>

      <InfoCard title="6 · Availability and warranties">
        <Paragraph>
          The app is provided "as is" and "as available", without warranties
          of any kind — including that it will be uninterrupted, error-free,
          or that AI features will always work (they depend on your key, your
          connection, and Google's service). Features may change, and parts of
          the app are still in development.
        </Paragraph>
      </InfoCard>

      <InfoCard title="7 · Limitation of liability">
        <Paragraph>
          To the maximum extent permitted by law, the developer of STRIX
          won't be liable for any indirect, incidental, or consequential
          damages — including lost data, lost profits, or decisions made based
          on AI output — arising from your use of the app. Your sole remedy
          is to stop using the app.
        </Paragraph>
      </InfoCard>

      <InfoCard title="8 · Acceptable use">
        <Paragraph>
          Use STRIX lawfully. Don't attempt to reverse engineer it for
          malicious purposes, don't use it to violate others' rights, and
          don't use it to generate or store content that's illegal where you
          live.
        </Paragraph>
      </InfoCard>

      <InfoCard title="9 · Changes">
        <Paragraph>
          These terms may be updated as the app evolves; the current version
          always lives in this screen. Continued use after a change means you
          accept the updated terms.
        </Paragraph>
      </InfoCard>
    </SettingsSubScreen>
  );
}
